# Generated by Django 5.1.2 on 2025-07-15 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelmasterapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.AddField(
            model_name="ip_rejection_table",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="cumulative_edit_difference",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="original_tray_qty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ip_rejection_table",
            name="rejection_count",
            field=models.PositiveIntegerField(
                help_text="Count of rejected items", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="plating_color",
            name="plating_color_internal",
            field=models.CharField(
                help_text="Short internal code used in stock number (e.g., B for Black)",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
