# Generated by Django 5.1.2 on 2025-07-28 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelmasterapp", "0002_delete_department_delete_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brass_qc_rejection_table",
            name="group",
        ),
        migrations.RemoveField(
            model_name="totalstockmodel",
            name="brass_saved_time",
        ),
        migrations.AddField(
            model_name="brass_qc_rejection_reasonstore",
            name="lot_rejected_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ip_rejection_draft",
            name="lot_rejection_remarks",
            field=models.CharField(
                blank=True,
                help_text="Lot rejection remarks for batch rejection",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ip_rejection_reasonstore",
            name="lot_rejected_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iqf_rejection_reasonstore",
            name="lot_rejected_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="bq_last_process_date_time",
            field=models.DateTimeField(
                blank=True, help_text="Last Process Date/Time", null=True
            ),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="brass_hold_lot",
            field=models.BooleanField(
                default=False, help_text="Indicates if the lot is on hold n Brass"
            ),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="brass_holding_reason",
            field=models.CharField(
                blank=True,
                help_text="Brass Reason for holding the batch",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="brass_release_lot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="brass_release_reason",
            field=models.CharField(
                blank=True,
                help_text="Brass Reason for releasing the batch",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="totalstockmodel",
            name="tray_verify",
            field=models.BooleanField(default=False, help_text="Tray Verify"),
        ),
        migrations.AddField(
            model_name="trayid",
            name="brass_rejected_tray",
            field=models.BooleanField(
                default=False, help_text="Is brass tray rejected"
            ),
        ),
        migrations.CreateModel(
            name="Brass_QC_Draft_Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_id", models.CharField(max_length=255)),
                ("batch_id", models.CharField(max_length=255)),
                ("draft_type", models.CharField(max_length=50)),
                ("draft_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("lot_id", "draft_type")},
            },
        ),
        migrations.CreateModel(
            name="Brass_TopTray_Draft_Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_id", models.CharField(max_length=255)),
                ("batch_id", models.CharField(max_length=255)),
                ("tray_id", models.CharField(max_length=255)),
                ("tray_qty", models.IntegerField()),
                ("delink_data", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("lot_id",)},
            },
        ),
    ]
