# Generated by Django 5.1.2 on 2025-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0003_department_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_user_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
